# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master


pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build'
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'DevComponents.DotNetBar2.dll'
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'IntelliLock.Console.exe'
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'IntelliLock.exe'
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'sqlite3_32_native.dll'
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'sqlite3_32_native.dll'
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'System.Data.SQLite.DLL'
- task: CmdLine@2
  inputs:
    script: '$(Agent.TempDirectory)\IntelliLock.Console.exe  -file $(Build.Repository.LocalPath)\bin\Release\netcoreapp2.2\pipelines-dotnet-core.dll'
- task: DotNetReactorTool@0
  inputs:
    version: '6.0.0.0'
    license: 'UG9seWZvbiB6d2l0c2NoZXJuZCBhw59lbiBNw6R4Y2hlbnMgVsO2Z2VsIFLDvGJlbiwgSm9naHVydCB1bmQgUXVhcms='
- task: ProtectWithDotNetReactor@1
  displayName: 'Protect With Dot Net Reactor'
